---
- hosts: all
  tasks:
    - name: install cocreate_platform service
      import_role:
        name: cocreate_platform
      tags:
        - cocreate_platform
      when: enable_cocreate_platform | bool
